library:
  source-dirs: src
tests:
  numconv-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - numconv
copyright: 2018 Olesya Chitaikina
maintainer: ch.olesya98@mail.ru
dependencies:
- base >= 4.7 && < 5
name: numconv
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Olesya Chitaikina
github: Yurry/numconv
license: BSD3
executables:
  numconv-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - numconv
description: Please see the README on GitHub at <https://github.com/githubuser/numconv#readme>
